#!/bin/bash
# =============================================================================
# NETTRADES.AI – Generate a secure .env file
# =============================================================================
# Usage: bash .env.generator.sh > .env
#        chmod 600 .env
#
# This script generates a complete .env file with strong random passwords
# for every service. It is provided as a convenience for users who want
# to generate secrets without running the full interactive wizard.
# The install-nettrades.sh script already does this internally; this
# standalone version can be used to rotate secrets or pre-generate a .env
# on a headless server.
#
# UPDATED (2026-06-29):
#   - Replaced MCP_API_KEY with PROXY_API_KEY (the new proxy authentication)
#   - Added ODOO_PROXY_URL and USE_ODOO_PROXY
# =============================================================================

cat << 'EOF'
# =============================================================================
# NETTRADES.AI – Environment Variables
# =============================================================================
# Generated by .env.generator.sh on $(date)
# Keep this file secure: chmod 600 .env
# =============================================================================

# -----------------------------------------------------------------------------
# Domain & Admin
# -----------------------------------------------------------------------------
DOMAIN=nettrades.ai
ADMIN_EMAIL=admin@nettrades.ai

# -----------------------------------------------------------------------------
# PostgreSQL
# -----------------------------------------------------------------------------
POSTGRES_PASSWORD=$(openssl rand -base64 24)
ADMIN_PASSWORD=$(openssl rand -base64 24)
SECRET_KEY=$(openssl rand -base64 32)

# -----------------------------------------------------------------------------
# Forgejo (Self-hosted Git Server)
# -----------------------------------------------------------------------------
FORGEJO_DB_PASSWORD=$(openssl rand -base64 24)
FORGEJO_SECRET_KEY=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -base64 32)

# -----------------------------------------------------------------------------
# Grafana
# -----------------------------------------------------------------------------
GRAFANA_PASSWORD=$(openssl rand -base64 12)

# -----------------------------------------------------------------------------
# LLM / AI
# -----------------------------------------------------------------------------
LLAMA_API_KEY=dummy
LANGGRAPH_API_KEY=$(openssl rand -base64 32)
ODOO_API_KEY=$(openssl rand -base64 24)

# -----------------------------------------------------------------------------
# Odoo Proxy (NEW – replaces mcp-odoo)
# -----------------------------------------------------------------------------
# This secret is used by BOTH the langgraph service (as ODOO_API_KEY) and the
# odoo-proxy service (as PROXY_API_KEY). They MUST be the exact same value.
PROXY_API_KEY=$(openssl rand -base64 32)
ODOO_PROXY_URL=http://odoo-proxy:3000
USE_ODOO_PROXY=true

# -----------------------------------------------------------------------------
# GPUStack
# -----------------------------------------------------------------------------
GPUSTACK_JWT_SECRET=$(openssl rand -base64 32)

# -----------------------------------------------------------------------------
# WireGuard
# -----------------------------------------------------------------------------
WIREGUARD_PRIVATE_KEY=$(wg genkey)
WIREGUARD_PUBLIC_KEY=$(echo "$WIREGUARD_PRIVATE_KEY" | wg pubkey)

# -----------------------------------------------------------------------------
# LangGraph PostgresSaver
# -----------------------------------------------------------------------------
DATABASE_URL=postgresql://odoo:${POSTGRES_PASSWORD}@postgres:5432/odoo

# -----------------------------------------------------------------------------
# GPU Registration Gate (Disabled by Default)
# -----------------------------------------------------------------------------
ENABLE_GPU_REGISTRATION=false

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
LOG_LEVEL=info
EOF