#!/bin/bash
# =============================================================================
# NETTRADES.AI – Generate a secure .env file
# =============================================================================
# Usage:  bash .env.generator.sh > .env
#         chmod 600 .env
#
# This script generates a complete .env file with strong random passwords
# for every service.  It is provided as a convenience for users who want
# to generate secrets without running the full interactive wizard.
# The install-nettrades.sh script already does this internally; this
# standalone version can be used to rotate secrets or pre-generate a .env
# on a headless server.
# =============================================================================

cat << 'EOF'
# =============================================================================
# NETTRADES.AI – Environment Variables
# =============================================================================
# Generated by .env.generator.sh on $(date)
# Keep this file secure: chmod 600 .env
# =============================================================================
DOMAIN=nettrades.ai
ADMIN_EMAIL=admin@nettrades.ai
POSTGRES_PASSWORD=$(openssl rand -base64 24)
ADMIN_PASSWORD=$(openssl rand -base64 24)
SECRET_KEY=$(openssl rand -base64 32)
FORGEJO_DB_PASSWORD=$(openssl rand -base64 24)
FORGEJO_SECRET_KEY=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -base64 32)
GRAFANA_PASSWORD=$(openssl rand -base64 12)
LLAMA_API_KEY=dummy
LANGGRAPH_API_KEY=$(openssl rand -base64 32)
ODOO_API_KEY=$(openssl rand -base64 24)
MCP_API_KEY=$(openssl rand -base64 32)
GPUSTACK_JWT_SECRET=$(openssl rand -base64 32)
WIREGUARD_PRIVATE_KEY=$(wg genkey)
WIREGUARD_PUBLIC_KEY=$(echo "$WIREGUARD_PRIVATE_KEY" | wg pubkey)
DATABASE_URL=postgresql://odoo:${POSTGRES_PASSWORD}@postgres:5432/odoo
EOF