# THIS IS A VERY OLD FILE GPUSTACK HAS BEEN REPLACED BY NVIDIA DYNAMO SO THIS COULD BE REMOVED 
# AND REPLACED WITH THE NVIDIA DYNAMO FILE
# FILE: deploy/kubernetes/apps/gpustack/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gpustack-server.yaml
  - wg-peer-manager.yaml