[options]
addons_path = /odoo-modules
data_dir = /var/lib/odoo
db_host = postgres
db_port = 5432
db_user = odoo
db_name = odoo
log_level = info
logfile = /var/log/odoo/odoo.log
workers = 0
db_password=odoonewpassword
