// =============================================================================
// Section: H – WireGuard Peer Manager
// -----------------------------------------------------------------------------
// This go.sum file is auto-generated by `go mod tidy`.
// Before building the Docker image, run:
//   cd distributed-gpu/controller/wg-peer-manager && go mod tidy
// The command will download dependencies and write the correct hashes.
// DO NOT manually edit this file.
// =============================================================================