#!/usr/bin/env python3
# =============================================================================
# FILE: odoo-modules/nettrades_gpu_admin/models/gpu_registration_token.py
# =============================================================================
# DESCRIPTION:
#   GPU Registration Token Model - stores pre-shared keys used for secure
#   GPU node registration. This implements a token-based authentication system
#   modeled after Tailscale's auth keys and Wiredoor's Personal Access Tokens.
#
#   Each token represents a permission for a specific node (or node type) to
#   join the GPU cluster. Tokens are:
#     - One-time use (by default, configurable)
#     - Time-limited (configurable expiration)
#     - Revocable by administrators
#     - Company-scoped (multi-tenant)
#     - Stored as SHA-256 hashes (never plaintext)
#
#   INDUSTRY BEST PRACTICES REFERENCED:
#     - Tailscale: Pre-authentication keys with expiry and tags
#     - Wiredoor: Personal Access Tokens (PATs) with per-node association
#     - DockNimbus: SHA-256 hashed tokens, single-use, 10-min expiry
#     - Odoo 19: API key authentication best practices
# =============================================================================

# -----------------------------------------------------------------------------
# IMPORTS – Each import MUST be on its own line for valid Python syntax.
# -----------------------------------------------------------------------------
from odoo import api, fields, models, _
from odoo.exceptions import ValidationError
import secrets
import hashlib
import logging
from datetime import timedelta

_logger = logging.getLogger(__name__)


class GpuRegistrationToken(models.Model):
    """
    GPU Registration Token - secure pre-shared keys for node onboarding.

    This model implements a secure token store for GPU node registration.
    Tokens are generated by administrators and distributed to node operators
    (freelancers, companies, researchers) out-of-band. The node presents the
    token during registration, and the system validates it against this store.

    Security Properties:
        - Tokens are stored as SHA-256 hashes (plaintext never persisted)
        - Tokens can be one-time use or reusable (configurable)
        - Tokens expire after a configurable duration
        - Tokens can be revoked by administrators
        - Tokens are scoped to a company (multi-tenant)
        - Token validation uses constant-time comparison via database lookup

    Lifecycle:
        1. Admin generates token via Odoo UI or API
        2. Token is hashed and stored; plaintext returned once to admin
        3. Admin shares token with node operator (out-of-band)
        4. Node presents token during GPU registration
        5. System validates token (hash match, not used, not revoked, not expired)
        6. Token is marked as used (if one-time)
        7. Node receives WireGuard configuration
    """
    _name = 'gpu.registration.token'
    _description = 'GPU Registration Token'
    _order = 'create_date DESC'
    _rec_name = 'name'

    # =========================================================================
    # Fields
    # =========================================================================

    name = fields.Char(
        string='Token Name',
        required=True,
        help='Human-readable name for this token (e.g., "Freelancer GPU Node - Alice")'
    )

    token_hash = fields.Char(
        string='Token Hash',
        required=True,
        index=True,
        readonly=True,
        help='SHA-256 hash of the token. The plaintext token is never stored.'
    )

    # Token metadata - what this token authorizes
    node_name = fields.Char(
        string='Node Name',
        help='Optional: specific node name this token is for. If set, the node must use this name during registration.'
    )

    node_public_key = fields.Char(
        string='Node Public Key',
        help='Optional: specific WireGuard public key this token is for. If set, only this key can register.'
    )

    allowed_ips = fields.Char(
        string='Allowed IPs',
        default='10.0.0.0/8',
        help='CIDR range(s) for IP allocation. Comma-separated. Defaults to 10.0.0.0/8.'
    )

    # Token lifecycle
    expires_at = fields.Datetime(
        string='Expires At',
        required=True,
        default=lambda self: fields.Datetime.now() + timedelta(days=7),
        help='Token expires after this date/time. Default: 7 days from creation.'
    )

    used_at = fields.Datetime(
        string='Used At',
        readonly=True,
        help='Timestamp when this token was used for registration.'
    )

    is_used = fields.Boolean(
        string='Is Used',
        default=False,
        index=True,
        help='True if this token has already been used for registration.'
    )

    is_revoked = fields.Boolean(
        string='Is Revoked',
        default=False,
        index=True,
        help='True if an administrator has revoked this token.'
    )

    is_one_time = fields.Boolean(
        string='One-Time Use',
        default=True,
        help='If True, token can only be used once. If False, token can be reused until expiry.'
    )

    # Relationships
    created_by = fields.Many2one(
        'res.users',
        string='Created By',
        default=lambda self: self.env.user,
        readonly=True,
        help='User who created this token.'
    )

    company_id = fields.Many2one(
        'res.company',
        string='Company',
        default=lambda self: self.env.company,
        required=True,
        help='Company this token belongs to (multi-tenant isolation).'
    )

    # =========================================================================
    # Constraints
    # =========================================================================

    _sql_constraints = [
        ('token_hash_unique', 'UNIQUE(token_hash)', 'Token hash must be unique.'),
    ]

    @api.constrains('expires_at')
    def _check_expires_at(self):
        """Ensure expiration is in the future."""
        for record in self:
            if record.expires_at and record.expires_at < fields.Datetime.now():
                raise ValidationError(_('Expiration date must be in the future.'))

    @api.constrains('is_used', 'is_revoked')
    def _check_used_revoked(self):
        """A token cannot be both used and revoked (redundant state)."""
        for record in self:
            if record.is_used and record.is_revoked:
                raise ValidationError(_('A token cannot be both used and revoked.'))

    # =========================================================================
    # Core Methods
    # =========================================================================

    @api.model
    def generate_token(self, name, **kwargs):
        """
        Generate a new registration token.

        Args:
            name (str): Human-readable name for the token
            **kwargs: Optional fields:
                - node_name (str): Specific node name
                - node_public_key (str): Specific WireGuard public key
                - allowed_ips (str): CIDR range(s)
                - expires_in_days (int): Days until expiration (default: 7)
                - is_one_time (bool): One-time use (default: True)

        Returns:
            tuple: (record, plaintext_token) where plaintext_token is the
                   raw token string to share with the node operator.

        Example:
            >>> token, plain = model.generate_token(
            ...     name="Alice's GPU Node",
            ...     node_name="alice-gpu-01",
            ...     expires_in_days=30
            ... )
            >>> print(plain)  # Share this with Alice
            'nt-abc123def456...'
        """
        # Generate a cryptographically secure random token
        # Format: nt-<32 random bytes in hex> (prefix for easy identification)
        random_bytes = secrets.token_bytes(32)
        plaintext_token = f"nt-{random_bytes.hex()}"

        # Hash the token for storage (SHA-256, one-way)
        token_hash = hashlib.sha256(plaintext_token.encode('utf-8')).hexdigest()

        # Calculate expiration
        expires_in_days = kwargs.get('expires_in_days', 7)
        expires_at = fields.Datetime.now() + timedelta(days=expires_in_days)

        # Build record values
        vals = {
            'name': name,
            'token_hash': token_hash,
            'node_name': kwargs.get('node_name'),
            'node_public_key': kwargs.get('node_public_key'),
            'allowed_ips': kwargs.get('allowed_ips', '10.0.0.0/8'),
            'expires_at': expires_at,
            'is_one_time': kwargs.get('is_one_time', True),
            'is_used': False,
            'is_revoked': False,
            'created_by': self.env.user.id,
            'company_id': self.env.company.id,
        }

        record = self.create(vals)
        _logger.info(
            "Generated GPU registration token '%s' (ID: %d) for user %s",
            name, record.id, self.env.user.login
        )

        return record, plaintext_token

    @api.model
    def validate_token(self, plaintext_token, node_public_key=None, node_name=None):
        """
        Validate a registration token.

        This is the core authentication method. It:
        1. Hashes the provided token
        2. Looks up the token by hash
        3. Validates: not used, not revoked, not expired
        4. Optionally validates node_name and node_public_key match
        5. Marks the token as used (if one-time)

        Args:
            plaintext_token (str): The raw token string from the request
            node_public_key (str, optional): The node's WireGuard public key
            node_name (str, optional): The node's reported name

        Returns:
            dict: Validation result with keys:
                - valid (bool): True if token is valid
                - token (gpu.registration.token, optional): The token record
                - error (str, optional): Error message if invalid

        Example:
            >>> result = model.validate_token(
            ...     "nt-abc123...",
            ...     node_public_key="AbC123...",
            ...     node_name="alice-gpu-01"
            ... )
            >>> if result['valid']:
            ...     token = result['token']
            ...     # Proceed with registration
        """
        # Step 1: Hash the provided token
        token_hash = hashlib.sha256(plaintext_token.encode('utf-8')).hexdigest()

        # Step 2: Look up the token by hash
        token = self.search([('token_hash', '=', token_hash)], limit=1)

        if not token:
            _logger.warning(
                "Token validation failed: token not found (hash: %s...)",
                token_hash[:8]
            )
            return {'valid': False, 'error': 'Invalid token'}

        # Step 3: Check if revoked
        if token.is_revoked:
            _logger.warning(
                "Token validation failed: token %s (ID: %d) has been revoked",
                token.name, token.id
            )
            return {'valid': False, 'error': 'Token has been revoked'}

        # Step 4: Check if expired
        if token.expires_at and token.expires_at < fields.Datetime.now():
            _logger.warning(
                "Token validation failed: token %s (ID: %d) expired at %s",
                token.name, token.id, token.expires_at
            )
            return {'valid': False, 'error': 'Token has expired'}

        # Step 5: Check if already used (for one-time tokens)
        if token.is_one_time and token.is_used:
            _logger.warning(
                "Token validation failed: one-time token %s (ID: %d) already used at %s",
                token.name, token.id, token.used_at
            )
            return {'valid': False, 'error': 'Token has already been used'}

        # Step 6: Validate node_name if specified on the token
        if token.node_name and node_name and token.node_name != node_name:
            _logger.warning(
                "Token validation failed: token %s requires node_name '%s', got '%s'",
                token.name, token.node_name, node_name
            )
            return {'valid': False, 'error': f'Token requires node_name: {token.node_name}'}

        # Step 7: Validate node_public_key if specified on the token
        if token.node_public_key and node_public_key and token.node_public_key != node_public_key:
            _logger.warning(
                "Token validation failed: token %s requires public key, mismatch",
                token.name
            )
            return {'valid': False, 'error': 'Token is bound to a specific public key'}

        # Step 8: Mark as used (if one-time)
        if token.is_one_time:
            token.write({
                'is_used': True,
                'used_at': fields.Datetime.now()
            })
            _logger.info(
                "Token %s (ID: %d) marked as used at %s",
                token.name, token.id, token.used_at
            )

        _logger.info(
            "Token %s (ID: %d) validated successfully for node %s",
            token.name, token.id, node_name or 'unnamed'
        )

        return {
            'valid': True,
            'token': token,
            'error': None
        }

    @api.model
    def revoke_token(self, token_id):
        """
        Revoke a token, preventing any future use.

        Args:
            token_id (int): ID of the token to revoke

        Returns:
            bool: True if revoked successfully
        """
        token = self.browse(token_id)
        if not token.exists():
            _logger.warning("Attempted to revoke non-existent token ID: %d", token_id)
            return False

        token.write({'is_revoked': True})
        _logger.info(
            "Token %s (ID: %d) revoked by user %s",
            token.name, token.id, self.env.user.login
        )
        return True