# =============================================================================
# Lead-Gen Agent - monitors platform activity, scores and creates leads.
# =============================================================================
import json, logging
from langgraph.graph import StateGraph, END, START
from langchain_openai import ChatOpenAI
from ..tools.inference_tools import get_inference_backend
from ..tools.odoo_tools import crm_lead_search, crm_lead_create

_logger = logging.getLogger(__name__)

class LeadGenState(dict):
    pass


def create_lead_gen_agent() -> StateGraph:
    backend = get_inference_backend()
    llm = ChatOpenAI(
        base_url=backend["base_url"],
        api_key=backend["api_key"],
        model=backend["model_name"],
        temperature=0.1,
    )

    async def scan_activity(state: LeadGenState):
        # Simulate scanning recent platform activity (simplified)
        leads = await crm_lead_search([], limit=10)
        state["recent_leads"] = leads
        return state

    async def score_and_create(state: LeadGenState):
        # Placeholder: actual scoring would analyse activity patterns.
        high_value = True  # simplistic
        if high_value:
            await crm_lead_create({
                "name": "Proactive Lead from platform activity",
                "description": "Generated by Lead-Gen Agent",
            })
        return state

    workflow = StateGraph(LeadGenState)
    workflow.add_node("scan_activity", scan_activity)
    workflow.add_node("score_and_create", score_and_create)
    workflow.add_edge(START, "scan_activity")
    workflow.add_edge("scan_activity", "score_and_create")
    workflow.add_edge("score_and_create", END)
    return workflow.compile()