# -*- coding: utf-8 -*-
# =============================================================================
# NETTRADES Core - NetTrades User Model
# =============================================================================
# FILE: odoo-modules/nettrades_core/models/nettrades_user.py
#
# PURPOSE:
#   This model stores all NetTrades-specific user data.
#   It is linked to the Odoo res.partner via a Many2one field, so that
#   existing Odoo customers can adopt NetTrades without modifying core tables.
#
# RELATIONSHIPS:
#   - partner_id -> res.partner (the Odoo partner record)
#   - review_ids -> nettrades.review (reviews received by this user)
#
# KEY FIELDS:
#   - karma, karma_score, reputation, wallet_address, is_verified, is_online, etc.
#
# UPDATES (2026-08):
#   - Created from former res_partner.py extensions.
#   - All NetTrades-specific fields are now here.
#   - Added review_ids field to fix @depends error.
#   - Added karma_score field (alias for karma, used in views).
#   - Added is_active field for soft deletion / activation.
# =============================================================================

from odoo import fields, models, api, _
from odoo.exceptions import ValidationError
import logging

_logger = logging.getLogger(__name__)


class NettradesUser(models.Model):
    _name = 'nettrades.user'
    _description = 'NetTrades User'
    _rec_name = 'partner_id'
    _order = 'create_date DESC'

    # =========================================================================
    # 1. Link to Odoo Core
    # =========================================================================

    partner_id = fields.Many2one(
        'res.partner',
        string='Partner',
        required=True,
        ondelete='cascade',
        help="Link to the Odoo partner record"
    )

    # =========================================================================
    # 2. NetTrades-Specific Fields
    # =========================================================================

    username = fields.Char(
        string='Username',
        help="NetTrades username"
    )

    wallet_address = fields.Char(
        string='Wallet Address',
        help="Blockchain wallet address for payments"
    )

    karma = fields.Integer(
        string='Karma',
        default=100,
        help="Reputation points earned from contributions."
    )

    # Alias field for views that expect 'karma_score'
    karma_score = fields.Integer(
        string='Karma Score',
        compute='_compute_karma_score',
        store=True,
        help="Computed alias for karma (used in views)."
    )

    reputation_score = fields.Float(
        string='Reputation Score',
        compute='_compute_reputation',
        store=True,
        help="Calculated reputation score based on karma and reviews."
    )

    is_verified = fields.Boolean(
        string='Verified',
        default=False,
        help="Whether the user has been verified"
    )

    is_online = fields.Boolean(
        string='Online',
        default=False,
        help="Whether the user is currently online"
    )

    is_active = fields.Boolean(
        string='Active',
        default=True,
        help="Whether the user account is active (soft delete)."
    )

    is_qualified = fields.Boolean(
        string='Is Qualified',
        default=False,
        help="Whether this user meets the qualification criteria."
    )

    qualification_reason = fields.Text(
        string='Qualification Reason',
        help="Reason for qualification or disqualification."
    )

    gpu_reputation = fields.Float(
        string='GPU Reputation',
        default=0.0,
        help="Reputation based on GPU contributions."
    )

    token_balance = fields.Float(
        string='Token Balance',
        default=0.0,
        help="Current token balance for GPU usage."
    )

    is_expert = fields.Boolean(
        string='Is Expert',
        default=False,
        help="Whether this user is a verified expert."
    )

    expert_rate = fields.Float(
        string='Expert Rate (per hour)',
        help="Hourly rate for expert consultations."
    )

    expert_bio = fields.Text(
        string='Expert Bio',
        help="Detailed bio for expert profile."
    )

    # Worker agent fields
    worker_agent = fields.Char(
        string='Worker Agent',
        help="The worker agent identifier for autonomous operations."
    )

    worker_context = fields.Json(
        string='Worker Context',
        help="JSON context for the worker agent."
    )

    worker_started = fields.Boolean(
        string='Worker Started',
        default=False,
        help="Whether the worker agent is currently running."
    )

    is_lead = fields.Boolean(
        string='Is Lead',
        default=False,
        help="Whether this partner is a lead generated by the AI."
    )

    # =========================================================================
    # 3. One2many Relations
    # =========================================================================

    review_ids = fields.One2many(
        'nettrades.review',
        'reviewed_partner_id',
        string='Reviews',
        help="Reviews received by this user"
    )

    # =========================================================================
    # 4. Computed Fields
    # =========================================================================

    @api.depends('karma')
    def _compute_karma_score(self):
        """Compute karma_score as a direct alias for karma."""
        for user in self:
            user.karma_score = user.karma

    @api.depends('karma', 'review_ids.rating')
    def _compute_reputation(self):
        for user in self:
            reviews = self.env['nettrades.review'].search([
                ('reviewed_partner_id', '=', user.partner_id.id)
            ])
            avg_review = sum(r.rating for r in reviews) / max(len(reviews), 1)
            user.reputation_score = (user.karma / 100.0) * 0.7 + (avg_review / 5.0) * 0.3

    # =========================================================================
    # 5. Constraints
    # =========================================================================

    @api.constrains('karma')
    def _check_karma(self):
        """Prevent negative karma values."""
        for user in self:
            if user.karma < 0:
                raise ValidationError(_("Karma cannot be negative."))

    @api.constrains('karma_score')
    def _check_karma_score(self):
        """Prevent negative karma_score values."""
        for user in self:
            if user.karma_score < 0:
                raise ValidationError(_("Karma Score cannot be negative."))

    # =========================================================================
    # 6. Helper Methods
    # =========================================================================

    @api.model
    def get_or_create(self, partner_id):
        """Get or create a NetTrades user for an Odoo partner."""
        user = self.search([('partner_id', '=', partner_id)], limit=1)
        if not user:
            partner = self.env['res.partner'].browse(partner_id)
            user = self.create({
                'partner_id': partner_id,
                'username': partner.email or partner.name,
            })
        return user

    def add_karma(self, amount, reason):
        """
        Add karma points to the user.
        """
        self.ensure_one()
        if not isinstance(amount, int):
            raise ValidationError(_("Karma amount must be an integer."))
        old_karma = self.karma
        self.karma += amount
        if self.karma < 0:
            self.karma = 0
        _logger.info(f"User {self.id} karma changed from {old_karma} to {self.karma} ({reason})")
        return self.karma